name: Nix Seed Build
description: Builder for Nix Seed

inputs:

  path:
    description: Path to flake.nix
    default: .

  github_token:
    description: GitHub Token

  cachix_name:
    description: Cachix cache name
    default: ${{ github.event.repository.name }}
  cachix_auth_token:
    description: Cachix auth token
  cachix_signing_key:
    description: Cachix signing key

runs:
  using: composite
  steps:
    - shell: bash
      run: |-
        set -x
        "$GITHUB_ACTION_PATH"/bin/build ${{ inputs.path }}
