name: Nix Zero Setup
description: Build and push pre-baked Nix environments to GHCR

inputs:
  github_token:
    description: GitHub Token for GHCR authentication
    required: true
  container_attr:
    description: Flake attribute of the container image to build
    default: .#build-container

runs:
  using: composite
  steps:
    - name: Nix Setup
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          accept-flake-config = true

    - name: Build and Push
      shell: bash
      run: |-
        # build
        nix build ${{ inputs.container_attr }}
        docker load < result
        # tag
        name=ghcr.io/${{ github.repository }}
        for tag in ${{ github.sha }} $(git describe --tags --always) latest; do
          docker tag ${{ github.event.repository.name }}:${{ github.sha }} $name:$tag
        done
        # push
        docker login ghcr.io \
          --username ${{ github.actor }} \
          --password-stdin <<< ${{ inputs.github_token }}
        docker push --all-tags $name
