name: Nix Seed Build
description: Builder for Nix Seed

inputs:

  path:
    description: Path to flake.nix
    default: .

  github_token:
    description: GitHub Token

  cachix_name:
    description: Cachix cache name
    default: ${{ github.event.repository.name }}
  cachix_auth_token:
    description: Cachix auth token
  cachix_signing_key:
    description: Cachix signing key

runs:
  using: composite
  steps:
    - name: pull seed
      shell: bash
      env:
        REGISTRY_USER: ${{ github.actor }}
        REGISTRY_PASS: ${{ inputs.github_token }}
      run: |-
        set -x
        lock=${{ inputs.path }}/.seed.lock
        seed=$(jq \
        --exit-status \
        --raw-output \
        --arg system "$(uname -m | sed s/arm64/aarch64/)-$(uname -s | tr '[:upper:]' '[:lower:]')" \
                                                                                                   '"\(.repository)@\(.systems[$system] // error("no seed digest for \($system)"))"' \
                                                                                                      $lock)

        podman login "${seed%%/*}" \
          --username "$REGISTRY_USER" \
          --password-stdin \
          <<<"$REGISTRY_PASS"
        podman pull $seed
    - name: build
      shell: bash
      run: |-
        set -x
        "$GITHUB_ACTION_PATH"/bin/build ${{ inputs.path }}
