name: Nix Seed Build
description: Builder for Nix Seed

inputs:

  path:
    description: Path to flake.nix
    default: .

  github_token:
    description: GitHub Token

runs:
  using: composite
  steps:
    - name: install oras
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH"/bin/install-oras
    - name: pull seed
      shell: bash
      env:
        REGISTRY_USER: ${{ github.actor }}
        REGISTRY_PASS: ${{ inputs.github_token }}
      run: |
        "$GITHUB_ACTION_PATH"/bin/pull-seed ${{ inputs.path }} "$RUNNER_TEMP/seed"
    - name: build
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH"/bin/build ${{ inputs.path }} "$RUNNER_TEMP/seed"
