name: seed-examples

on:
  push:
    branches:
      - master
    paths:
      - examples/*/flake.lock
      - .github/workflows/seed-examples.yaml
  workflow_dispatch:

jobs:
  seed:
    permissions:
      contents: write
      id-token: write
      packages: write
    strategy:
      matrix:
        example:
          - rust
          - python
          - cpp-boost
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./seed
        with:
          path: examples/${{ matrix.example }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
